import net.fabricmc.loom.task.RemapJarTask

architectury {
    common(enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/controllerx.accesswidener")
}

sourceSets {
    api {
        java {
            srcDir "src/api/java"

            runtimeClasspath += configurations.api
            compileClasspath += configurations.api
        }
    }

    main {
        resources {
            runtimeClasspath += sourceSets.api.output
            compileClasspath += sourceSets.api.output
        }
    }
}

configurations {
    api {
        canBeResolved = true
    }

    apiImplementation.extendsFrom compileClasspath
}

dependencies {
    // We depend on fabric loader here to use the fabric @Environment annotations and get the mixin dependencies
    // Do NOT use other classes from fabric loader
    modImplementation "net.fabricmc:fabric-loader:$fabric_loader_version"
    // Remove the next line if you don't want to depend on the API
    modApi "dev.architectury:architectury:$architectury_version"

    modImplementation "fuzs.forgeconfigapiport:forgeconfigapiport-common:8.0.0"

    implementation("io.github.libsdl4j:libsdl4j:$libsdl4j_version")
    modImplementation("dev.ultreon.mods:ultreonlib:$ultreonlib_version")
    api("dev.ultreon.corelibs:corelibs-collections-v0:$corelibs_version")
    api("dev.ultreon.corelibs:corelibs-commons-v0:$corelibs_version")
    api("dev.ultreon.corelibs:corelibs-crash-v0:$corelibs_version")
    api("dev.ultreon.corelibs:corelibs-datetime-v0:$corelibs_version")
    api("dev.ultreon.corelibs:corelibs-events-v1:$corelibs_version")
    api("dev.ultreon.corelibs:corelibs-functions-v0:$corelibs_version")
    api("dev.ultreon.corelibs:corelibs-registries-v0:$corelibs_version")
    api("dev.ultreon.corelibs:corelibs-text-v0:$corelibs_version")
    api("dev.ultreon.corelibs:corelibs-translations-v0:$corelibs_version")

    modImplementation("dev.ultreon.mods:advanced-debug:$advancedDebugVersion")

    // Mixin Extras
    annotationProcessor(compileOnly("io.github.llamalad7:mixinextras-common:0.4.1"))
}

publishing {
    publications {
        mavenCommon(MavenPublication) {
            artifactId = rootProject.archives_base_name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
    }
}

jar {
    from sourceSets.api.output
}

tasks.register("apiJar", Jar) {
    archiveClassifier.set("api")
    from sourceSets.api.output
    archiveBaseName.set("api-dev")
}

remapJar.dependsOn("apiJar")

tasks.register("remapApiJar", RemapJarTask) {
    inputFile.set(tasks.apiJar.archiveFile)
    dependsOn tasks.apiJar
    archiveClassifier.set("api")
}
